# Change these first
owner: chintan9 # Your GitHub organization or username, where this repository lives
repo: MyDNS # The name of this repository

sites:
  - name: MyDNS
    url: https://dot.dnsc9.dynv6.net/login.html
  - name: MyDNS
    url: https://dnsc9.dynv6.net/login.html
  - name: CloudFlare DNS 1
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: CloudFlare DNS 2
    check: "tcp-ping"
    url: 1.0.0.1
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: chintan9.github.io
  baseUrl: /MyDNS
  logoUrl: https://raw.githubusercontent.com/chintan9/MyDNS/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "status page for My DNS"
  introMessage: Uptime monitor and status page for dot.dnsc9.dynv6.net
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO    
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
